name: CI/CD
on:
  push:
    branches:
      - qa
      - master
      - release

env:
  author: shenxuxiang

jobs:
  job-1:
    name: Build Task
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.head_commit.message, 'build') }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Compute Time
        id: timestamp
        run: |
          echo "::set-output name=timestamp::$(echo $(date --date="now + 8 hours" +%Y-%m-%d%t%H:%M:%S))"

      - name: Echo Time
        run: |
          echo ${{ steps.timestamp.outputs.timestamp }}


      # - name: Build Code
      #   run: |
      #     npm run build
      #     tar -czvf dist.tar.gz ./dist





