name: CI/CD
on:
  push:
    branches:
      - qa
      - master
      - release

env:
  author: shenxuxiang

jobs:
  job-1:
    name: Build Task
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.head_commit.message, 'build') }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Compute Time
        id: timestamp
        run: |
          echo "::set-output name=timestamp::$(echo $(date --date="now + 8 hours" +%Y-%m-%d%t%H:%M:%S))"

      - name: Echo Time
        run: |
          echo ${{ steps.timestamp.outputs.timestamp }}

    outputs:
      output1: ${{ steps.timestamp.outputs.timestamp }}
      # - name: Build Code
      #   run: |
      #     npm run build
      #     tar -czvf dist.tar.gz ./dist

  job-2:
    name: Test Task
    runs-on: ubuntu-latest
    needs: job-1
    env:
      ref: ${{ github.ref }}
      ref_name: ${{ github.ref_name }}
      ref_type: ${{ github.ref_type }}
      event_name: ${{ github.event_name }}
      author: ${{ github.event.head_commit.committer.username }}
      email: ${{ github.event.head_commit.committer.email }}
      timestamp: ${{ needs.job-1.outputs.output1 }}
    steps:
      - name: Echo Env
        run: |
          echo "ref: ${ref}"
          echo "ref_name: ${ref_name}"
          echo "ref_type: ${ref_type}"
          echo "event_name: ${event_name}"
          echo "author: ${author}"
          echo "email: ${email}"
          echo "time: ${timestamp}"
          echo "output1:" ${{ needs.job-1.outputs.output1 }}



